### ISSUE TITLE
a few minor preliminary observations

### ISSUE THREAD

**Issue by amtoine** [fdncred/nufmt#1]
hellord :wave: 

here i finally am :relieved: :muscle: 

i've started by pulling you're repo, fired up `cargo doc` and had a look at the source.

## two preliminary points
- [x] maybe we could get rid of `g.nu` and `gradient.nu` right? :thinking: 
they look super old => `nushell` version `0.31.x` :open_mouth: 
they do not appear anywhere else in the repo :confused: 
```bash
> rg \.nu **/*.rs | lines | parse "{file}:{match}"
╭───┬──────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────╮
│ # │       file       │                                              match                                              │
├───┼──────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ src/main.rs      │             windows_output_default_file = Some(file.replace(".nu", "_f.nu"))                    │
│ 1 │ benches/bench.rs │ /// You need a nu file called massive.nu in your project root                                   │
│ 2 │ benches/bench.rs │     let file = fs::read_to_string("massive.nu").expect("massive.nu file in project directory"); │
╰───┴──────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────╯
```
> :green_circle: done in #3
- [x] also what about renaming `readme.md` into `README.md`? this might be a bit more conventional, you tell me :yum: 
> :green_circle: done in #2 

i know this is very superficial, but i wanted to have a look at the stuff around the `rust` source before diving in, and the two points above are what came to me :wink: 

for now, cheers :yum:

**Comment by fdncred** [comment]
Hey, Welcome! :)

> maybe we could get rid of g.nu and gradient.nu right?

They were put there just to be an example of files to play with formatting on. I have no doubt they're outdated now.

> also what about renaming readme.md into README.md? this might be a bit more conventional, you tell me

whatev - i'm good with either.

> i know this is very superficial,...

no worries. have fun. i hope you come up with something great!

**Comment by amtoine** [comment]
> They were put there just to be an example of files to play with formatting on. I have no doubt they're outdated now.
> 
oooooh wow, i understand what they are here for :laughing: :+1: 
makes perfect sense

> whatev - i'm good with either.
>
gotcha :ok_hand: 
 
> no worries. have fun. i hope you come up with something great!
>
i'll see what i can think of :smirk:

**Comment by amtoine** [comment]
i did not see anything in `awesome-nu` about formatting...
is this project the only one in this direction? :open_mouth:

**Comment by fdncred** [comment]
This project does not work at all. It was a simple json formatter, and I thought I could easily and quickly make it a nushell formatter. I was wrong. So, if this every gets finished, i'll go in awesome-nu.  I know of no other projects to format nushell scripts.

**Comment by amtoine** [comment]
> This project does not work at all. It was a simple json formatter, and I thought I could easily and quickly make it a nushell formatter. I was wrong. So, if this every gets finished, i'll go in awesome-nu. I know of no other projects to format nushell scripts.
>
ok i see :+1:

**Comment by amtoine** [comment]
i did not see this was completed in #3 :ok_hand:
